name: Test GitHub Variables

on:
  workflow_dispatch

jobs:
  hello_world:
      runs-on: ubuntu-latest
      steps:
        - name: Use variable
          run: |
            echo "repo var TEST_VARIABLE is ${{ vars.TEST_VARIABLE }}"
